# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f178d6e27ae11b5620b2d5836804d4f0fc6ee3d67705090f56f3f9fcf5f7d139963626095956b5e4b8a3d903de80d1e5fd433b4631f07e4e79c6804b0fc9dcfe

test:
  secret_key_base: ae99b63e81b8ef41da491c434bfb2d60c7bb9071772950a272daa1344046ebeaa20c868e3bfeb8b7ffe60f40c0919e2e2d2459d41e83a103708ea02f7ee04e08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
